name: Build n Push to ECR
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WAS_IMAGE_NAME: petclinic-was
      WEB_IMAGE_NAME: petclinic-web
      WAS_VERSION: v1.0.0
      WEB_VERSION: v1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build WAR
        run: |
          cd petclinic_btc
          mvn clean package -DskipTests -PMySQL

      #---------Build WAS Image----------#
      - name: Build Tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          WAS_IMAGE_TAG="${WAS_VERSION}-${SHORT_SHA}"
          echo "WAS_IMAGE_TAG=$WAS_IMAGE_TAG" >> $GITHUB_ENV
      - name: Build & Tag WAS image
        run: |
          docker build -t $WAS_IMAGE_NAME:$WAS_IMAGE_TAG ./petclinic_btc
          docker tag $WAS_IMAGE_NAME:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPO_WAS }}:$WAS_IMAGE_TAG
      - name: Push WAS
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPO_WAS }}:$WAS_IMAGE_TAG

      # --------Build WEB Image--------- #
      - name: Build WEB Tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          WEB_IMAGE_TAG="${WEB_VERSION}-${SHORT_SHA}"
          echo "WEB_IMAGE_TAG=$WEB_IMAGE_TAG" >> $GITHUB_ENV
      - name: Build & Tag WEB image
        run: |
          cd ..
          docker build -t $WEB_IMAGE_NAME:$WEB_IMAGE_TAG .
          docker tag $WEB_IMAGE_NAME:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPO_WEB }}:$WEB_IMAGE_TAG
      - name: Push WEB
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPO_WEB }}:$WEB_IMAGE_TAG















